image:
  - Visual Studio 2017
  - Ubuntu

platform:
  - x64

environment:
  nodejs_version: 10.3.0

cache:
  - node_modules
  - '%USERPROFILE%\.electron'

init:
  - git config --global core.autocrlf input

install:
  - cmd: powershell Install-Product node $env:nodejs_version x64
  - sh: nvm install $nodejs_version
  - yarn

build_script:
  - cmd: yarn pbuild -w
  - sh: yarn pbuild -l

test: off
